### PR TITLE
Fix blink when favorite

### LINKED ISSUE #202: Blink time when favorite
## Kind (Required)

- Improvement

 ## Overview (Required)

- ⏲ 
like_time

 ## Links	

-

### PR DESCRIPTION
**Pull request by yt8492**
## Issue
- close #202 

## Overview (Required)
- use forEachIndexed
- remove `lastStartTimeText` and get last session each loop

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by yurihondo** [comment]
👀

File: feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/widget/SessionsItemDecoration.kt [hunk 1]
```diff
@@ -38,18 +38,17 @@ class SessionsItemDecoration(
...
+        parent.forEachIndexed { index, view ->
             val position = parent.getChildAdapterPosition(view)
             if (position == RecyclerView.NO_POSITION) return
 
             val sessionItem = adapter.getItem(position) as SessionItem
             val startTimeText = calcTimeText(position, view)
 
-            lastStartTimeText?.let {
-                if (sessionItem.startSessionTime() == it.value) return@forEach
+            if (index > 0) {
```
Comment (yt8492) [inline feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/widget/SessionsItemDecoration.kt]: First, I tried
```
val layoutManager = parent.layoutManager as LinearLayoutManager
val topVisibleItemPosition = layoutManager.findFirstVisibleItemPosition()
if (position > topVisibleItemPosition) {
    val lastSessionItem = adapter.getItem(position - 1) as SessionItem
    if (sessionItem.startSessionTime() == lastSessionItem.startSessionTime()) return@forEach
}
```
but, first element of forEach and element at topVisibleItemPosition are not same, so flickering occured when scrolling. So I use `forEachIndexed` and check top element using index.
