### PR TITLE
Adds the workaround to fix issue #118

### LINKED ISSUE #118: Filters are not exists on Android 5.0
## Kind (Required)

- Improvement

 ## Overview (Required)

- 

image

### PR DESCRIPTION
**Pull request by crimsonwoods**
## Issue
- close #118 

## Overview (Required)
- Perform view layout explicitly

### CODE REVIEW

File: feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionsFragment.kt [hunk 1]
```diff
@@ -179,6 +181,22 @@ class SessionsFragment : DaggerFragment() {
             ) { checked, level ->
                 sessionsViewModel.filterChanged(level, checked)
             }
+
+            if (Build.VERSION.SDK_INT == Build.VERSION_CODES.LOLLIPOP) {
```
Comment (crimsonwoods) [inline feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionsFragment.kt]: For `LOLLIPOP_MR1`, I don't know that this workaround is needed or not.
I hope that someone verify this workaround on Lollipop MR1 device.

**Comment by takahirom** [comment]
Thank you. Interesting.

File: feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionsFragment.kt (hunk 1 above)
Comment (eyedol) [reply feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionsFragment.kt]: I applied your fix to a branch I'm working on to fix #122  -- It worked flawlessly, however, your fix #118 wasn't quite consistent. Upon the first launch, it works but when you press say the back button and launch the app, the filters and the day 1 list are not shown. Though the favorite icon keeps work. See attached gif

fix-layout-issue

**Comment by takahirom** [comment]
Thank you! I don't know the cause but I will try to merge.

File: feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionsFragment.kt (hunk 1 above)
Comment (crimsonwoods) [reply feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SessionsFragment.kt]: @eyedol Thank you for reporting and sharing. And sorry for late replying.
Currently, I have no idea to solve that problem about the process of restoring views. Because I don't understand what is happening at restoring.

@takahirom Have you created the issue reported at above comment?
