### PR TITLE
[iOS] Fix Makefile

### LINKED ISSUE #667: [iOS] Failed to build SwiftGen
**Overview (Required)**
- Failed to build SwiftGen.

**Steps To Reproduce**

1. Go to `ios_base` directory.
2. Run `make init`
3. `Failed to build SwiftGen 6.1.0 with SPM`

**Expected behavior**
the build to be success.
 
**Env:**
 - OS: MacOS 10.15.3
- Xcode 11.3.1
 - master branch / 2bedc70e496d3abc207754cd2a178e96b626d86e

**Error Log**

```
mint run swiftgen swiftgen
🌱  Using SwiftGen/SwiftGen 6.1.0 from Mintfile.
🌱  Cloning SwiftGen 6.1.0
🌱  Resolving package
🌱  Building package
[1/10] Compiling writer.c
[2/10] Compiling scanner.c
[3/10] Compiling reader.c
[4/10] Compiling parser.c
[5/10] Compiling emitter.c
[6/10] Compiling api.c
[7/11] Compiling Kanna CSS.swift
/private/var/folders/r9/d3j1xpps38q2h51974d_hvgw0000gn/T/mint/github.com_SwiftGen_SwiftGen/.build/checkouts/Kanna/Modules/libxml2-kanna.h:1:9: note: while building module 'libxml2' imported from /private/var/folders/r9/d3j1xpps38q2h51974d_hvgw0000gn/T/mint/github.com_SwiftGen_SwiftGen/.build/checkouts/Kanna/Modules/libxml2-kanna.h:1:
#import <libxml2/libxml/HTMLtree.h>
        ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "libxml/HTMLparser.h"
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/libxml2/libxml/HTMLparser.h:15:10: error: 'libxml/xmlversion.h' file not found
#include <libxml/xmlversion.h>
         ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "libxml2-kanna.h"
        ^
/private/var/folders/r9/d3j1xpps38q2h51974d_hvgw0000gn/T/mint/github.com_SwiftGen_SwiftGen/.build/checkouts/Kanna/Modules/libxml2-kanna.h:1:9: error: could not build module 'libxml2'
#import <libxml2/libxml/HTMLtree.h>
        ^
/private/var/folders/r9/d3j1xpps38q2h51974d_hvgw0000gn/T/mint/github.com_SwiftGen_SwiftGen/.build/checkouts/Kanna/Sources/Kanna/CSS.swift:27:8: error: could not build Objective-C module 'libxmlKanna'
import libxmlKanna
       ^
'SwiftClibxml2' /private/var/folders/r9/d3j1xpps38q2h51974d_hvgw0000gn/T/mint/github.com_SwiftGen_SwiftGen/.build/checkouts/SwiftClibxml2: warning: system packages are deprecated; use system library targets instead
🌱  Encountered error during "swift build -c release -Xswiftc -target -Xswiftc x86_64-apple-macosx10.15". Use --verbose to see full output
🌱  Failed to build SwiftGen 6.1.0 with SPM
make: *** [swiftgen] Error 1
```

### PR DESCRIPTION
**Pull request by 417-72KI**
## Issue
- N/A

## Overview (Required)
- `make init` command
  - Create shell script.
    - Install all dependencies(e.g. `rbenv`, `mint`) if not installed.
  - This may resolve #667 
- `xcode` may need `swiftgen`.
- `make` to run `xcode` target

## Links
- no link

### CODE REVIEW

File: ios-base/scripts/bootstrap.sh [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+    brew install rbenv rbenv-communal-gems
+
+    cat << EOS >> ~/.zshrc
+    if which rbenv > /dev/null; then eval "\$(rbenv init -)"; fi
+    export PATH="\$HOME/.rbenv/bin:\$PATH"
+    eval "\$(rbenv init -)"
+EOS
+fi
+
+source ~/.zshrc
```
Comment (ry-itto) [inline ios-base/scripts/bootstrap.sh]: Hmm... This script supports only `zsh`. We should support other shells.
But I don't have any idea... 😢

Comment (417-72KI) [reply ios-base/scripts/bootstrap.sh]: I think iOS developer should use `zsh` because it has become default shell in macOS now.

If you insist to use bash, my solution is using `$SHELL`.

```sh
if [ "$SHELL" = '/bin/bash' ]; then
    source ~/.bashrc
elif [ "$SHELL" = '/bin/zsh' ]; then
    source ~/.zshrc
else
    echo "Unsupported shell: ${SHELL}"
    exit 1
fi
```

Comment (ry-itto) [reply ios-base/scripts/bootstrap.sh]: I see. OK. Please add this script? And then I will merge this 🙏

Comment (417-72KI) [reply ios-base/scripts/bootstrap.sh]: Fixed in 52c5dfea

**Comment by roana0229** [comment]
Thank you as always 😄
