### PR TITLE
Fix SessionsViewModelTest fail

### LINKED ISSUE #697: Fix SessionsViewModelTest fail
## Kind (Required)

- Improvement

 ## Overview (Required)

- SessionsViewModelTest test is broken 😭 
image

 ## Links	

-

### PR DESCRIPTION
**Pull request by sekiya9311**
## Issue
- close #697 

## Overview (Required)
- Add mock of `SessionAlarm` class
- Add verify test of `toggleRegister()`

### CODE REVIEW

File: feature/session/src/test/java/io/github/droidkaigi/confsched2020/session/ui/viewmodel/SessionsViewModelTest.kt [hunk 1]
```diff
@@ -26,12 +27,14 @@ class SessionsViewModelTest {
...
     @MockK(relaxed = true) lateinit var sessionRepository: SessionRepository
+    @MockK lateinit var sessionAlarm: SessionAlarm
 
     @Test
     fun load() {
         coEvery { sessionRepository.sessionContents() } returns flowOf(Dummies.sessionContents)
         coEvery { sessionRepository.refresh() }
-        val sessionsViewModel = SessionsViewModel(sessionRepository = sessionRepository)
+        val sessionsViewModel =
+            SessionsViewModel(sessionRepository = sessionRepository, sessionAlarm = sessionAlarm)
```
Comment (takahirom) [inline feature/session/src/test/java/io/github/droidkaigi/confsched2020/session/ui/viewmodel/SessionsViewModelTest.kt]: Can you use this form? 🙏 
https://developer.android.com/kotlin/style-guide#functions

```kotlin
val sessionsViewModel = SessionsViewModel(
    sessionRepository = sessionRepository, 
    sessionAlarm = sessionAlarm
)
```

Comment (sekiya9311) [reply feature/session/src/test/java/io/github/droidkaigi/confsched2020/session/ui/viewmodel/SessionsViewModelTest.kt]: Oh, I didn't know style guide. 😅
Of course I do !

**Comment by takahirom** [comment]
Thanks! LGTM!
