### PR TITLE
fix SearchSessionFragment : remember query text

### LINKED ISSUE #348: When come back to search screen after query searching, editText become empty
## Kind (Required)

- Improvement

 ## Overview (Required)

- Should retype queried text from saved at viewModel instance.
    - Currently, search result list is displaying filtered list when coming back.

 ## Links	
👀 
https://github.com/DroidKaigi/conference-app-2020/blob/7e4a56cc15be5cca58c7f8c70d72ad810fecb344/feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/viewmodel/SearchSessionsViewModel.kt#L19

### PR DESCRIPTION
**Pull request by nredjap**
fix SearchSessionFragment : remember query text, when come back after query searching

## Issue
- close #348 

## Overview (Required)
- Set(≒initialize) query text in `SearchSessionsFragment::onCreateOptionsMenu`.
(`SearchSessionsFragment::onCreateOptionsMenu`でクエリテキストの設定をしました。)
- Second arg of `searchView.setQuery()` is `false`. Because I think submit is unnecessary, In this case `searchResult` is remembered in `SearchSessionsViewModel`.
(`searchView.setQuery()`の第２引数は`false`にしています。この時検索結果はViewModelに覚えられていて、submitが不要と考えているためです。)

## Links
- none.

## Screenshot
- none.

Please let me know if there are strange points in my code & PR.🙏🙏🙏
(変なところがあったら教えてください！🙏🙏🙏)

### CODE REVIEW

File: feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SearchSessionsFragment.kt [hunk 1]
```diff
@@ -157,6 +157,7 @@ class SearchSessionsFragment : DaggerFragment() {
             ContextCompat.getColor(requireContext(), R.color.search_close_icon)
         )
         searchView.isIconified = false
+        searchView.setQuery(searchSessionsViewModel.uiModel.value!!.searchResult.query, false)
```
Comment (takahirom) [inline feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SearchSessionsFragment.kt]: You can use uiModel.requireValue() for it 🙏

Comment (takahirom) [reply feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SearchSessionsFragment.kt]: Let me think some minutes 🙇

Comment (takahirom) [reply feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SearchSessionsFragment.kt]: Thank you for your PR. I thought a little based on your plan.
How about this?

```kotlin
data class UiModel(val searchResult: SearchResult) {
        fun isEmpty() = this == EMPTY

        companion object {
            val EMPTY = UiModel(SearchResult.EMPTY)
        }
    }
```

```
val searchResult = searchSessionsViewModel.uiModel.requireValue().searchResult
if (!searchResult.isEmpty()) {
  searchView.setQuery(searchResult.query, false)
}
```

Comment (nredjap) [reply feature/session/src/main/java/io/github/droidkaigi/confsched2020/session/ui/SearchSessionsFragment.kt]: I checked about LiveData.requireValue(). I should have used that.
Thank you for teaching 🙏🙏

and...
thank you code sample😭 I'll repair PR now.

**Comment by nredjap** [comment]
sorry! I missed the sample...🙇
Which is preferred? The latter is now committed.
```
data class UiModel(val searchResult: SearchResult) {
        fun isEmpty() = this == EMPTY

        companion object {
            val EMPTY = UiModel(SearchResult.EMPTY)
        }
    }
```
```
val uiModel = searchSessionsViewModel.uiModel.requireValue()
if (!uiModel.isEmpty()) {
  searchView.setQuery(uiModel.searchResult.query, false)
}
```
or
```
class SearchResult(
    val sessions: List<Session>,
    val speakers: List<Speaker>,
    val query: String?
) {
    fun isEmpty() = this == EMPTY

    companion object {
        val EMPTY = SearchResult(listOf(), listOf(), null)
    }
}
```
```
        val searchResult = searchSessionsViewModel.uiModel.requireValue().searchResult
        if (!searchResult.isEmpty()) {
            searchView.setQuery(searchResult.query, false)
        }
```

**Comment by takahirom** [comment]
Thanks for suggestions! 🔍 
Personally, there is a possibility that UiModel has something other than search results, so SearchResult seems better.

**Comment by nredjap** [comment]
thank you review.🙏
`Searcgresykt.isEmpty()` version is already committed. Because I noticed "missed the sample" after committed... 🙇
So, don't I need to commit anymore fix? (「なので、これ以降の修正は不要でしょうか？」的な意味のことを言いたいです...)

(「`SearchResult.isEmpty` のほうがベターだね」という読み取りをしています。そもそも間違っていたらすみません...)

**Comment by takahirom** [comment]
Sorry for my bad English 🙇 
You are correct!

**Comment by takahirom** [comment]
LGTM! Thank you for fixing this issue!

**Comment by nredjap** [comment]
thank you comment!
This PR was an irreplaceable experience for me.
